### PR TITLE
Migrate from glif graphql & filfox to Beryx

### PR DESCRIPTION
**Pull request by juliangruber**
As discussed in https://filecoinproject.slack.com/archives/C03PVLW721L/p1709027221851889, we should migrate away from using Glif's GraphQL API. While we're at it, also migrate away from Filfox, as they don't offer an official API.

Don't merge this before we have received permission by Beryx/Zondax to use their API. If they don't give us permission, invalidate the token.

I've tested this PR and the API is smooth and responsive :)

### CODE REVIEW

**Comment by juliangruber** [comment]
We got permission 🥳

**Comment by juliangruber** [comment]
@bajtos hindsight please

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/desktop/releases/tag/v1.3.14

**Review by bajtos — COMMENTED** [review]
LGTM 👍🏻

**Pull request merged**
