### PR TITLE
Frontend file structure proposal

### PR DESCRIPTION
**Pull request by davelange**
Proposal for the new file structure convention to be used for v2.

### CODE REVIEW

**Comment by bajtos** [comment]
The high-level proposal looks good to me. Great idea! 👍🏻

**Comment by juliangruber** [comment]
bump @davelange

**Comment by juliangruber** [comment]
ping @davelange

**Comment by davelange** [comment]
Sorry for the delay. Is there anything missing here regarding the frontend?

**Comment by juliangruber** [comment]
The main comment says "still in progress". Is this ready for review?

**Comment by davelange** [comment]
> The main comment says "still in progress". Is this ready for review?

Yes, just updated the comment

**Review by juliangruber — CHANGES_REQUESTED** [review]

**Pull request merged**
