### PR TITLE
upgrade to latest electron

### PR DESCRIPTION
**Pull request by juliangruber**
This release has the latest currently available security patches (see https://github.com/electron/electron/releases?page=1)

I took another look at upgrading to 23 and beyond, but couldn't yet figure out the click issues.

### CODE REVIEW

**Comment by juliangruber** [comment]
Ok I just found something out:

If you comment out this, it works:

```css
  body {
    @apply font-body text-black overflow-x-hidden;
    -webkit-user-select: none;
    /* -webkit-app-region: drag; */
  }
```

Looks like with the newer chrome version something can be either draggable or clickable, but not both?

**Comment by juliangruber** [comment]
That was easier than I thought, assuming we are ok giving up draggable on the modal background (ok with me)

**Comment by juliangruber** [comment]
confirmed via https://github.com/electron/electron/issues/1354

**Review by bajtos — APPROVED** [review]
👌🏻 

I am excited that we are again on the latest Electron version! 💪🏻

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/desktop/releases/tag/v0.20.1

**Pull request merged**
