### PR TITLE
ci: use WIN_* prefix for CSC config

### PR DESCRIPTION
**Pull request by bajtos**
Rename the following environment variables in the packaging step:
- `CSC_LINK` to `WIN_CSC_LINK`
- `CSC_KEY_PASSWORD` to `WIN_CSC_KEY_PASSWORD`

The goal is to fix the following error reported by our CI:

```
Env WIN_CSC_LINK is not correct, cannot resolve: D:\a\desktop\desktop not a file
```

### CODE REVIEW

**Comment by bajtos** [comment]
See https://github.com/filecoin-station/desktop/pull/944#issuecomment-1704882268

**Comment by bajtos** [comment]
The CI passed, and the problem seems fixed.

I am not sure, though, what will happen when we run a release build - will we get a properly signed binary?

**Review by juliangruber — APPROVED** [review]
> The CI passed, and the problem seems fixed.
> 
> I am not sure, though, what will happen when we run a release build - will we get a properly signed binary?

I don't know! According to [docs](https://www.electron.build/code-signing), there shouldn't even be a difference in the first place:

Screenshot 2023-09-04 at 12 28 12

You can next create a pre-release, and I can test it on my windows machine.

**Comment by juliangruber** [comment]
Yes and yes 👍  Or use `npm version`

**Comment by bajtos** [comment]
The draft release: https://github.com/filecoin-station/desktop/releases/tag/untagged-a3a59818a065198f8606

**Comment by juliangruber** [comment]
The release opened without issues 👍

**Pull request merged**
